alias composer='docker compose exec app composer'
alias pa='docker compose exec app php artisan'
alias pamm='docker compose exec app php artisan make:model'
alias paabout='docker compose exec app php artisan about'
alias paapidocs='docker compose exec app php artisan docs:generate-all'
alias parl='docker compose exec app php artisan route:list'
alias pa-migrate='docker compose exec app php artisan migrate'
alias pa-migrate-fresh='docker compose exec app php artisan migrate:fresh --seed'
alias padbseed='docker compose exec app php artisan db:seed'
alias padbseed-fresh='docker compose exec app php artisan db:seed --force'
alias patest='docker compose exec app php artisan test'
alias paphpunit='docker compose exec app ./vendor/bin/phpunit'
alias paphpstan='docker compose exec app ./vendor/bin/phpstan'

